<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [4]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
greeting("Batman")

'Hello Batman! So, nice to meet you!'

In [13]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])
list_mean

3.0

### 1.2 Named functions that don’t return

In [19]:

def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'
greeting("Batman")


'Hello Batman! So, nice to meet you!'

### 1.3 Anonymous functions

In [ ]:

# Your code here


### 1.4 Optional arguments

In [ ]:

# Your code here


## 2 The importance of functions?

### 2.1 An argument for functions

### 2.2 A word of caution

## Exercise 1 :  Do you know why?




return f'hello {name}!' itself acts as an else statement as it will output any other input that is not 'Batman'.




## Exercise 2 :  Calculator functions

In [25]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
def add(x,y):
    return x + y
add (x,y)



array([100, 100, 100, 100, 100])

In [28]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
def yuan_zhe(x,y):
    return x - y 
yuan_zhe(x,y)

array([-28, -32, -12,  52, -46])

In [29]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
def yuan_zhe_function_multiply(x,y):
    return x*y 
yuan_zhe_function_multiply(x,y)

array([2304, 2244, 2464, 1824, 1971])

In [41]:
y = np.array([0, 1, 2])
(y==0).any()

True

In [59]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
def divide(x,y):
    if (y==0).any():
        return "array cannot contain 0"
    return x/y

divide(x, y)

'array cannot contain 0'

## Exercise 3 :  max_info() with NumPy

In [57]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
def max_info(numbers):
    return np.max(numbers),np.argmax(numbers)
max_info(numbers)


(83, 2)

In [58]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
np.max(numbers)
#this just figuring out who np.max works

83