<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
import numpy as np

In [ ]:

# Your code here


### 1.2 Accessing data from a list (or array)

In [6]:

py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
print(py_real_names[2])
print(py_super_names[1])
print(py_real_names[-2])

Stephen Strange
Iron Man
Tony Stark


### 1.3 Accessing data from a dictionary

In [13]:

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange",
                  "Yuan Zhe": "SPS God"
                  }
print(superhero_info["Yuan Zhe"])
superhero_info.keys()


SPS God


dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange', 'Yuan Zhe'])

In [14]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange', 'SPS God'])

### 1.4 Higher dimensional lists

In [17]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]
print(py_superhero_info[2])

['Stephen Strange', 'Doctor Strange']


## 2 Lists vs. Arrays

### 2.1 Size

In [19]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
len(py_list_2d)


10

In [20]:
len(np_array_2d)

10

In [21]:
np_array_2d.shape

(10, 2)

### 2.2 Arrays are fussy about type

In [24]:

py_list = [1, 1.5, "A"]
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [27]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [29]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)
py_list_1 + py_list_2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [30]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [32]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)      
py_list*4

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [33]:
np_array*4

array([ 4,  8, 12, 16, 20])

### 2.6 Squaring

In [34]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
np_array**2


array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [40]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
np_array == 3  



array([False, False,  True, False, False])

In [39]:
np_array > 3  

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [41]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
sum(py_list)     # sum() is a base Python function

15

In [42]:
max(py_list)     # max() is a base Python function

5

In [43]:
np_array.mean()

3.0

## Exercise 1 :  Total recall?

similarity 1: both can store data
similarity 2: both can run mathematical functions
difference 1: numpy only can store 1 kind of data, python can store multiple kind of data (eg. python can store int and str but numpy only can store int at one go)
difference 2: list multiplication makes a list repeat and grow whereas array multiplication multiplies the elements within the array by the factor

*Dictionaries use a key and an associated value separated by a :, can store data. Basically, it associates 1 data to another*



## Exercise 2 :  Index me

In [59]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0],py_list[2],py_list[4],py_list[6],py_list[8])



a1 c3 e5 g7 i9


## Exercise 3 :  Capitalise Heros

In [50]:


superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()  
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
print (superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [57]:

numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]          
np_array_1=np.array(numbers)
np_array_2=np_array_1 == 1
np_array_2.sum()




9